# KGLRR specific
kgcn: "RGAT"
latent_dim_rec: 64
lightGCN_n_layers: 3
dropout: 1

r_logic: 1.0e-4
r_length: 1.0e-5
l2_loss: 1.0e-4
loss_sum: False

batch_size: 1024

layers: 1
maxhis: 10
sim_scale: 10

save_dataset: False
explain: False