name: Build, test with matrix, then lint

on: [
  # push,
  pull_request,
  workflow_dispatch
]

jobs:
  sync_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        env: [cpu, cu118, cu121, cu124]
        python-version: ["3.9", "3.10", "3.11"]
        experimental: [false]
        include:
          - python-version: "3.12"
            os: ubuntu-latest
            experimental: true
          - os: windows-latest
            python-version: "3.9"
            experimental: true
          - os: windows-latest
            python-version: "3.10"
            experimental: true
          - os: windows-latest
            python-version: "3.11"
            experimental: true
          - os: windows-latest
            python-version: "3.12"
            experimental: true

    uses: ./.github/workflows/sync_and_test.yml
    with:
      env: ${{ matrix.env }}
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
      experimental: ${{ matrix.experimental }}

  lint:
    needs: sync_and_test
    uses: ./.github/workflows/lint.yml
    with:
      python-version: 3.10
      os: ubuntu-latest