name: Sync with uv and test

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
      experimental:
        required: true
        type: boolean

jobs:
  sync:
    uses: ./.github/workflows/sync.yml
    with:
      env: ${{ inputs.env }}
      python-version: ${{ inputs.python-version }}
      os: ${{ inputs.os }}
      experimental: ${{ inputs.experimental }}
  test:
    needs: sync
    runs-on: ${{ inputs.os }}
    outputs:
      test_status: ${{ steps.test_project.outputs.status }}

    steps:
      - name: Install project
        uses: ./.github/workflows/sync.yml
        with:
          env: ${{ inputs.env }}
          python-version: ${{ inputs.python-version }}
          os: ${{ inputs.os }}
          experimental: ${{ inputs.experimental }}
      - name: Test Overall
        run: |
          uv run -m pytest -v -n auto tests/config
      - name: Test metrics
        run: |
          uv run -m pytest -v -n auto tests/metrics
      - name: Test data
        run: |
          uv run -m pytest -v -n auto tests/data
      - name: Test evaluation_setting
        run: |
          uv run -m pytest -v -n auto tests/evaluation_setting
      - name: Test model
        if: inputs.experimental == 'false' && inputs.os == 'ubuntu-latest'
        run: |
          uv run -m pytest -v -n auto tests/model/test_model_auto.py
      - name: Test hyper_tuning
        run: |
          uv run -m pytest -v tests/hyper_tuning/test_hyper_tuning.py
      - name: Output test status
        id: test_project
        run: |
          echo "status=success" >> $GITHUB_OUTPUT
